name: transport-tracker
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.1.1
  - requests=2.31.0
  - pydeck=0.8.0b3
  - plotly=5.16.1
  - pip
  - pip:
      - streamlit==1.30.0
      - uvicorn==0.23.2
