name: sti
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.28.0
      - pandas==2.1.0
      - requests==2.32.0
      - python-dotenv==1.0.0
      - pydeck>=0.9.0
